config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'
  get 'empresa', to: 'pages#empresa'
  get 'clientes', to: 'pages#clientes'
  get 'resultados', to: 'pages#resultados'
  get 'servicos/1', to: 'pages#servicos1'
  get 'servicos/2', to: 'pages#servicos2'
  get 'contato', to: 'pages#contato'
  post 'contact', to: 'contacts#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :check_email

  def create
    if ContactMailer.with(contact_params).contact_email.deliver_later
      flash[:notice] = "Mensagem enviada com sucesso"
      redirect_to contato_path
    else
      flash[:alert] = "Algo deu errado :("
      redirect_to contato_path
    end
  end

  private

    def contact_params
      params.permit(:name, :email, :subject, :message)
    end

    def check_email
      if params[:email].empty?
        flash[:alert] = "Preencha seu endereço de e-mail corretamente"
        redirect_to contato_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  def empresa
  end
  def clientes
  end
  def resultados
  end
  def servicos1
  end
  def servicos2
  end
  def contato
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="decorFooter">
    <%= image_tag "decorFooter.svg", size:"100", class: "" %>
  </div>
  <div class="container">
    <div class="columns">
      <div class="column">
        <strong>Empresa</strong>
        <%= link_to 'Quem somos', empresa_path %>
        <%= link_to 'Nossa equipe', empresa_path %>
      </div>
      <div class="column">
        <strong>Serviços</strong>
        <%= link_to 'Condomínios e indivíduos', servicos_1_path %>
        <%= link_to 'Grandes empresas e serviços públicos', servicos_2_path %>
      </div>
      <div class="column">
        <strong>Outros links</strong>
        <%= link_to 'Clientes', clientes_path %>
        <%= link_to 'Resultados', resultados_path %>
        <%= link_to 'Contato', contato_path %>
      </div>
    </div>
    <%= link_to image_tag("logoFooter.svg", size:"225"), root_path %>
  </div>
</footer>

app/views/layouts/_header.html.erb
<%= javascript_pack_tag 'nav', defer: 'true' %>
<nav class="navbar is-transparent" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
        <%= link_to image_tag("logo.svg", size:"225"), root_path, class:'navbar-item' %>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="pwNavbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-end">
      <div id="pwNavbar" class="navbar-menu">
        <%= link_to 'EMPRESA', empresa_path, class: 'navbar-item' %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link is-arrowless">
            SERVIÇOS
          </a>

          <div class="navbar-dropdown is-boxed">
            <a href="/servicos/1" class="navbar-item">
              Condomínios e <br />Clientes Individuais
            </a>
            <a href="/servicos/2" class="navbar-item">
              Grandes Clientes e <br />Serviços Públicos
            </a>
          </div>
        </div>

        <%= link_to 'CLIENTES', clientes_path, class: 'navbar-item' %>

        <%= link_to 'RESULTADOS', resultados_path, class: 'navbar-item' %>
        <div class="navbar-item">
          <%= link_to 'CONTATO', contato_path, class:'button contactMenu' %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_header_home.html.erb
<%= javascript_pack_tag 'nav', defer: 'true' %>
<nav class="navbar home is-transparent" role="navigation" aria-label="main navigation">
  <div class="container">
    <div class="navbar-brand">
     <%= link_to image_tag("logoLight.svg", size:"225"), root_path, class:'navbar-item' %>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="pwNavbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-end">
      <div id="pwNavbar" class="navbar-menu">
        <%= link_to 'EMPRESA', empresa_path, class: 'navbar-item' %>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link is-arrowless">
            SERVIÇOS
          </a>

          <div class="navbar-dropdown is-boxed">
            <a href="/servicos/1" class="navbar-item">
              Condomínios e <br />Clientes Individuais
            </a>
            <a href="/servicos/2" class="navbar-item">
              Grandes Clientes e <br />Serviços Públicos
            </a>
          </div>
        </div>

        <%= link_to 'CLIENTES', clientes_path, class: 'navbar-item' %>

        <%= link_to 'RESULTADOS', resultados_path, class: 'navbar-item' %>
        <div class="navbar-item">
          <%= link_to 'CONTATO', contato_path, class:'button contactMenu' %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectWay<%= content_for?(:title) ? ' · ' : '' %><%= yield :title %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'favicon.png', type: 'image/png' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if content_for?(:navbar) %>
      <%= yield(:navbar) %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>
    <%= yield %>
    <% if content_for?(:footer) %>
      <%= yield(:footer) %>
    <% else %>
      <%= render 'layouts/footer' %>
    <% end %>
  </body>
</html>

app/views/pages/clientes.html.erb
<% provide(:title, "Clientes") %>
<section class="section">
  <div class="container">
    <div class="title">Clientes</div>
    <div class="columns is-multiline">
      <div class="column is-3 is-flex">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag "clientes/naturgy.jpg" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <p class="title is-6">Naturgy</p>
              <p class="text">
                Concessionária de Distribuição de Gás Canalizado no Estado do RJ
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-3 is-flex">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag "clientes/oceanfront.jpg" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <p class="title is-6">Ocean Front Resort</p>
              <p class="text">
                Condomínio - Barra da Tijuca
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-3 is-flex">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag "clientes/alfaquality.jpg" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <p class="title is-6">Alfa Quality</p>
              <p class="text">
                Condomínio - Barra da Tijuca
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-3 is-flex">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag "clientes/riviera.jpg" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <p class="title is-6">Riviera</p>
              <p class="text">
                Condomínio - Barra da Tijuca
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="column is-3 is-flex">
        <div class="card">
          <div class="card-image">
            <figure class="image">
              <%= image_tag "clientes/portofino.jpg" %>
            </figure>
          </div>
          <div class="card-content">
            <div class="content">
              <p class="title is-6">Porto Fino</p>
              <p class="text">
                Condomínio - Barra da Tijuca
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/contato.html.erb
<% provide(:title, "Contato") %>

<section class="section">
  <div class="container">
    <div class="title">
      Contato
    </div>
    <div class="columns is-centered">
      <div class="column is-4">
        <%= form_with(url: contact_path, method: "post") do |f| %>
        <div class="field">
          <label class="label">Nome</label>
          <div class="control">
            <%= f.text_field :name, class: 'input', placeholder: 'Seu nome' %>
          </div>
        </div>
        <div class="field">
          <label class="label">E-mail</label>
          <div class="control">
            <%= f.email_field :email, class: 'input', placeholder: 'nome@exemplo.com' %>
          </div>
        </div>
        <div class="field">
          <label class="label">Assunto</label>
          <div class="control">
            <%= f.text_field :subject, class: 'input', placeholder: 'Assunto' %>
          </div>
        </div>
        <div class="field">
          <label class="label">Mensagem</label>
          <div class="control">
            <%= f.text_area :message, class: 'textarea', placeholder: 'Escreva sua mensagem...' %>
          </div>
        </div>
        <div class="field">
          <div class="control">
            <%= f.submit "Enviar mensagem", class: 'button is-link' %>
          </div>
        </div>
        <% end %>
        <% if flash[:notice] %>
          <article class="message is-success">
            <div class="message-body">
              <%= flash[:notice] %>
            </div>
          </article>
        <% elsif flash[:alert] %>
          <article class="message is-danger">
            <div class="message-body">
              <%= flash[:alert] %>
            </div>
          </article>
        <% end %>
      </div>
      <div class="column is-4 is-offset-1 has-background-white-ter is-flex is-hidden">
        <p>
          <strong>Telefone:</strong> &nbsp; (21) 99000-0000
          <br />
          <br />
          <strong>Barra da Tijuca</strong>
          <br />
          Rio de Janeiro/RJ - Brasil
        </p>
      </div>
    </div>
  </div>
</section>

app/views/pages/empresa.html.erb
<% provide(:title, "Empresa") %>
<section class="section">
  <div class="container">
    <div class="title">Quem somos</div>
    <div class="text has-text-justified">
      <p>
        A <strong>Projectway</strong> é formada por profissionais de
        reconhecida experiência no mercado,
        com resultados individuais de grande relevância que
        se reuniram em busca de
        um objetivo comum, que é prestar serviços
        diferenciados, inovadores e com custo
        adequado, buscando as melhores soluções para os
        clientes.
      </p>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="title">Nossa equipe</div>
    <div class="columns">
      <div class="column is-flex is-narrow">
        <div class="card">
          <div class="card-content">
            <p class="title is-5">Gleizer Rocha</p>
            <p class="text">
              Engª, Arquiteta, Urbanista, Contadora, <br />
              Engª Segurança, Perita Judicial, <br />
              Consultora Técnica em Eficiência Energética e Engenharia.
            </p>
          </div>
        </div>
      </div>
      <div class="column is-flex is-narrow">
        <div class="card">
          <div class="card-content">
            <p class="title is-5">Patrícia Novo</p>
            <p class="text">
              Engª Perita Judicial, <br />
              Consultora Técnica em Eficiência Energética e Engenharia.
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/pages/index.html.erb
<% provide(:title, "Soluções em engenharia para seu negócio") %>
<% content_for :navbar do %>
  <%= render 'layouts/header_home' %>
<% end %>

<section class="homeHero">
  <%= image_tag "heroBg.jpg", size:"100%", class: "" %>
  <div class="container">
    <div class="heroTitle">
      Soluções em engenharia <br />
      para o seu negócio
    </div>
    <a href="/empresa">Saiba mais -></a>
  </div>
</section>

<section class="section services">
  <div class="container">
    <div class="selectServices">
      <div class="secTitle">
        Serviços
      </div>
      <div class="secDesc">
        Selecione o <strong>perfil</strong> em que você se identifica
      </div>
    </div>
    <div class="selectOptions">
      <a href="/servicos/1">
        <div class="card">
          <div>
            <div class="servIcon">
              <%= image_tag "condIcon.svg", size:"115", class: "" %>
            </div>
            <div class="servTitle">
              Condomínios e <br />
              Clientes Individuais
            </div>
          </div>
        </div>
      </a>
      <a href="/servicos/2">
        <div class="card">
          <div>
            <div class="servIcon">
              <%= image_tag "industryIcon.svg", size:"115", class: "" %>
            </div>
            <div class="servTitle">
              Grandes Clientes e <br />
              Concessionárias de <br />
              Serviços Públicos
            </div>
          </div>
        </div>
      </a>
    </div>
  </div>
</section>

app/views/pages/resultados.html.erb
<% provide(:title, "Resultados") %>
<section class="section">
  <div class="container">
    <div class="title">Resultados</div>
    <div class="columns is-variable is-5">
      <div class="column is-4">
        <div class="title is-6">Demandas Judiciais</div>
        <p class="text has-text-justified">
          Os nossos pareceres técnicos, elaborados sob a ótica pericial, resultam em <strong class="has-text-link">decisões favoráveis</strong> para nossos clientes, seja confirmando o cabimento das ações ou revertendo entendimentos desfavoráveis.
        </p>
      </div>
      <div class="column is-4">
        <div class="title is-6">Recuperação Creditícia</div>
        <p class="text has-text-justified">
          As ações da Projectway proporcionaram aos nossos clientes a recuperação de recursos financeiros da ordem de <strong class="has-text-link">milhões de reais</strong>, seja no suporte a renegociações contratuais ou na emissão de pareceres técnicos.
        </p>
      </div>
      <div class="column is-4">
        <div class="title is-6">Assistência Regulatória</div>
        <p class="text has-text-justified">
          A consultoria tem grande expertise na atuação em processos regulatórios, <strong class="has-text-link">obtendo excelentes resultados</strong> na redução ou exclusão de multas regulatórias e decisões favoráveis aos nossos clientes.
        </p>
      </div>
    </div>
  </div>
</section>

app/views/pages/servicos1.html.erb
<% provide(:title, "Serviços Para Condomínios e Clientes Individuais") %>
<%= javascript_pack_tag "items", defer: 'true' %>

<section class="section">
  <div class="container">
    <div class="title">
      Serviços
    </div>
    <div class="subtitle is-uppercase is-spaced">
      Condomínios e Clientes Individuais
    </div>

    <div class="title service is-4">
      Consultoria Operacional
    </div>
    <div class="columns is-multiline">
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Diagnóstico Operacional da Edificação
          </div>
          <div class="itemDesc">
            Avaliação da infraestrutura do condomínio e os seus processos, como consumo de água, consumo de gás, de energia elétrica, bem como os equipamentos que compõem os sistemas.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Avaliação da Performance Energética dos Processos
          </div>
          <div class="itemDesc">
            Verificação de como e quando a energia é utilizada, qual a eficiência dos equipamentos e identificar desperdícios de energia.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Análise dos Contratos de Prestação de Serviços (Serviços Concedidos)
          </div>
          <div class="itemDesc">
            Análise das contas de consumo, buscando avaliar oportunidades de economia.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Definição de novos padrões de performance energética
          </div>
          <div class="itemDesc">
            Apresentação de um procedimento para verificação de oportunidades de Eficiência Energética nos Processos do condomínio. Elaboração de Relatório de performance de redução de consumo de energia.
          </div>
        </div>
      </div>
    </div>

    <hr />

    <div class="title service is-4">
      Gestão Condominal
    </div>
    <div class="columns is-multiline">
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Assistência Técnica para Demandas Judiciais
          </div>
          <div class="itemDesc">
            Elaboração de estratégia, emissão de Pareceres e Notas Técnicas, Quesitação, Acompanhamento de Diligências Periciais, Testes em Laboratórios, Análise de processos judiciais sob a ótica pericial.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Assessoria em Processos de Contratação de Empresas
          </div>
          <div class="itemDesc">
            Análise das necessidades do condomínio, elaboração de editais de licitação, emissão de termos de referência e assessoria ao condomínio na seleção dos prestadores de serviços.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Assessoria para manutenção, reformas e serviços técnicos em geral
          </div>
          <div class="itemDesc">
            Elaboração de critérios de execução, controle de qualidade, movimentação financeira dos serviços.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Representação junto aos órgãos oficiais e demais instituições
          </div>
          <div class="itemDesc">
            Assessoria técnica junto à Prefeitura e Concessionárias de Serviços Públicos.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Treinamentos
          </div>
          <div class="itemDesc">
            Aplicação de treinamentos voltados à Segurança Operacional, Prevenção de Acidentes, Serviços Administrativos, etc.
          </div>
        </div>
      </div>
    </div>

    <hr />

    <div class="title service is-4">
      Gestão de Projetos e Obras
    </div>
    <div class="columns is-multiline">
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Diagnóstico Pré-obra
          </div>
          <div class="itemDesc">
            Execução de autovistoria predial segundo a Lei Estadual nº 6.400 de 05 de março de 2013, Lei Complementar nº 2963 de 11 de junho de 2012, Decreto nº 37.426 de 11 de julho 2013, PLS 491/2011, Inspeção Periódica de gás (autovistoria), Lei Estadual 6.890 de 2014, vistorias pontuais, conforme a necessidade do contratante.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Gerenciamento de Projetos
          </div>
          <div class="itemDesc">
            Acompanhamento de projetos de construções ou reformas, desde a elaboração até a entrega dos serviços.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Assessoria em Licitação de Obras
          </div>
          <div class="itemDesc">
            Elaboração de editais e assessoria na seleção dos prestadores de serviços.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Gerenciamento e Fiscalização de Obras
          </div>
          <div class="itemDesc">
            Fiscalização da execução dos serviços contratados, documentação da empresa executora e dos funcionários, acompanhamento dos serviços, buscando a otimização dos custos, controle de qualidade e análise de relatórios.
          </div>
        </div>
      </div>
    </div>

    <hr />

    <div class="title service is-4">
      Avaliações Patrimoniais e Econômicas
    </div>

    <div class="columns is-multiline">
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Avaliação de Ativos
          </div>
          <div class="itemDesc">
            A Projectway oferece aos seus clientes a avaliação dos ativos, uma vez que,
            sem avaliações frequentes as empresas desconhecem o retorno do capital
            investido, porque o valor de mercado de um ativo é alterado ao longo do
            tempo, de acordo com sua depreciação física e fatores econômicos.
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Quando é necessária a avaliação dos ativos?
          </div>
          <div class="itemDesc">
            <ul type="disc">
              <li>Seguros de bens patrimoniais;</li>
              <li>Avaliações para suporte de reestruturação societária (Lei das S/A);</li>
              <li>Realização de incorporações;</li>
              <li>Impugnação de valor venal – IPTU;</li>
              <li>Garantias para obtenção de financiamentos;</li>
              <li>Reavaliação de ativos imobilizados;</li>
              <li>Negociações como vendas, fusões, cisões, aquisições e joint-ventures;</li>
              <li>Para capitalização de Fundos de Previdência;</li>
              <li>Nacionalização de máquinas e equipamentos- visa atender portarias nº 8
              do MICT 370/94 e 150 do DECEX, Departamento de Comércio Exterior.</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Por que fazer a avaliação dos ativos?
          </div>
          <div class="itemDesc">
            <ul type="disc">
              <li>Tomar conhecimento do valor justo de mercado de um ativo;</li>
              <li>Suporte à tomada de decisões gerenciais;</li>
              <li>Redução de custos;</li>
              <li>Registro do Patrimônio.</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            O que avaliar?
          </div>
          <div class="itemDesc">
            <ul type="disc">
              <li>Imóveis comerciais, residenciais e rurais tais como prédios, casas,
              apartamentos, lojas e sobrelojas, glebas, terrenos, fazendas, etc;</li>
              <li>Máquinas e equipamentos;</li>
              <li>Móveis e utensílios;</li>
              <li>Empreendimentos imobiliários: hotéis, parques temáticos, shopping centers,
              supermercados, hospitais;</li>
              <li>Empreendimentos de base industrial: complexos industriais tais como
              frigoríficos, agroindústrias, refinarias, estaleiros e indústrias de transformação;</li>
              <li>Veículos, aeronaves e embarcações.</li>
            </ul>
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Teste de Impairment- Lei 11.638/2007
          </div>
          <div class="itemDesc">
            <p>Teste de recuperabilidade, para a avaliação da condição de liquidez dos ativos
            fazendo uma correlação com seus valores de mercado e fluxos de caixa.</p> <br />
            <p>Consiste, basicamente, na realização de uma avaliação patrimonial do bem para
            mensurar seu justo valor de mercado, elaborada mediante a aplicação dos conceitos
            técnicos definidos pela Engenharia de Avaliação. </p> <br />
            <p>Com a realização deste Teste de Impairment as demonstrações contábeis da empresa
            passam a estar “de acordo” com as práticas contábeis em vigor no Brasil, e
            consequentemente, em condições de serem auditadas por Auditor Independente sem
            qualquer ressalva e/ou contestação. </p> <br />
            <b>Leia mais:</b>
            <a href="http://static.cpc.aatb.com.br/Documentos/26_CPC%2001%20R1%20Termo%2
0de%20Aprova%C3%A7%C3%A3o.pdf" target="_blank">Documento 1</a> |
            <a href="http://static.cpc.aatb.com.br/Documentos/28_CPC01R1_Sumario.pdf" target="_blank">Documento 2</a>
          </div>
        </div>
      </div>
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Reavaliação do Ativo Imobilizado - Lei 11638
          </div>
          <div class="itemDesc">
            <p>A Reavaliação dos bens patrimoniais (ativo imobilizado) tem a finalidade de
            adequação à Lei 11638 e IFRS e são realizados conforme as recomendações das
            NBR 14653 da ABNT- Associação Brasileira de Normas Técnicas, IBAPE – Instituto
            Brasileiro de Avaliações e Perícia de Engenharia de São Paulo, INMETRO – Instituto
            Nacional de Metrologia, Normalização e Qualidade Industrial e Normas
            internacionalmente reconhecidas para fins de avaliação de ativo imobilizado –
            Internacional Valuation Satandard Council (IVSC).</p> <br />
            <p>Os Laudos de Avaliação são elaborados com a relação de bens inventariados e
            conciliados com os respectivos registros contábeis por componente, com a utilização
            dos mesmos critérios de abertura dos itens registrados na contabilidade, com
            descritivo da metodologia utilizada, premissas técnicas: manutenção das máquinas,
            instalação e formas de operação das máquinas, planejamento de substituição das
            máquinas, evolução tecnológica, base de cálculos, pesquisa no mercado, etc de forma
            verificar os valores valor de mercado, valor líquido de venda (CPC 01), Valor residual
            final (CPC 27), Custo atribuído (Deemed Cost), Vida útil econômica, conforme a
            finalidade contratada.</p>
          </div>
        </div>
      </div>
    </div>

    <hr />

    <div class="title service is-4">
      Perícias e Vistorias
    </div>

    <div class="columns is-multiline">
      <div class="column is-narrow">
        <div class="item">
          <div class="itemTitle">
            Assessoria
          </div>
          <div class="itemDesc">
            <p>
              Assessoramento em todas as etapas de processos judiciais, extrajudiciais, que
              envolvam discussão de valores e matéria técnica de engenharia, tais como:
            </p> <br />
            <p>
              <ul type="disc">
                <li>Danos construtivos;</li>
                <li>Impermeabilizações e obras de modo geral;</li>
                <li>Laudos e Pareceres Extra Judiciais;</li>
                <li>Ações renovatórias;</li>
                <li>Desapropriações;</li>
                <li>Inventários;</li>
                <li>Falências;</li>
                <li>Demarcações;</li>
                <li>Seguros;</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </div>

  </div>
</section>